services:
  telegram-bot:
    build: .
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    networks:
      - bot-network
    restart: unless-stopped

  max-bot:
    build: .
    environment:
      - PLATFORM=max
      - BOT_TOKEN=${MAX_BOT_TOKEN}
      - GROUP_CHAT_ID=${MAX_GROUP_CHAT_ID}
    restart: unless-stopped

  webhook:
      image: python:3.11-slim
      container_name: deploy-webhook
      restart: always
      working_dir: /app
      volumes:
        - .:/app
        - /var/run/docker.sock:/var/run/docker.sock
      env_file:
        - .env
      ports:
        - "9000:9000"
      command: python webhook.py

networks:
  bot-network:
    driver: bridge
